routes/web.php
                    Route::post('delete-selected', [Backend\Uploads\UserUploadsController::class, 'destroySelected'])->name('destroy.selected');
                });
                Route::name('guests.')->prefix('guests')->group(function () {
                    Route::get('/', [Backend\Uploads\GuestUploadsController::class, 'index'])->name('index');
                    Route::get('{shared_id}/view', [Backend\Uploads\GuestUploadsController::class, 'view'])->name('view');
                    Route::get('{shared_id}/download', [Backend\Uploads\GuestUploadsController::class, 'downloadFile'])->name('download');
                    Route::delete('{shared_id}', [Backend\Uploads\GuestUploadsController::class, 'destroy'])->name('destroy');
                    Route::post('delete-selected', [Backend\Uploads\GuestUploadsController::class, 'destroySelected'])->name('destroy.selected');
                });
            });
            Route::name('reports.')->prefix('reports')->group(function () {
                Route::get('/', [Backend\FileReportController::class, 'index'])->name('index');
                Route::get('{id}/view', [Backend\FileReportController::class, 'view'])->name('view');
                Route::post('{id}/view', [Backend\FileReportController::class, 'markAsReviewed'])->name('markAsReviewed');
                Route::delete('{id}/delete', [Backend\FileReportController::class, 'destroy'])->name('destroy');
            });
            Route::middleware('saas')->group(function () {
                Route::resource('subscriptions', 'SubscriptionController');
                Route::resource('transactions', 'TransactionController');
                Route::resource('plans', 'PlanController');
                Route::resource('coupons', 'CouponController');
            });
            Route::get('advertisements', [Backend\AdvertisementController::class, 'index'])->name('advertisements.index');
            Route::get('advertisements/{id}/edit', [Backend\AdvertisementController::class, 'edit'])->name('advertisements.edit');
            Route::post('advertisements/{id}', [Backend\AdvertisementController::class, 'update'])->name('advertisements.update');
        });
        Route::prefix('navigation')->namespace('Navigation')->name('admin.')->middleware('demo')->group(function () {
            Route::post('navbarMenu/sort', [Backend\Navigation\NavbarMenuController::class, 'sort'])->name('navbarMenu.sort');
            Route::resource('navbarMenu', 'NavbarMenuController');
            Route::post('footerMenu/sort', [Backend\Navigation\FooterMenuController::class, 'sort'])->name('footerMenu.sort');
            Route::resource('footerMenu', 'FooterMenuController');
        });
        Route::prefix('blog')->namespace('Blog')->middleware('demo', 'disable.blog')->group(function () {
            Route::get('categories/slug', [Backend\Blog\CategoryController::class, 'slug'])->name('categories.slug');
            Route::resource('categories', 'CategoryController');
            Route::get('articles/slug', [Backend\Blog\ArticleController::class, 'slug'])->name('articles.slug');
            Route::get('articles/categories/{lang}', [Backend\Blog\ArticleController::class, 'getCategories'])->middleware('ajax.only');
            Route::resource('articles', 'ArticleController');
            Route::get('comments', [Backend\Blog\CommentController::class, 'index'])->name('comments.index');
            Route::get('comments/{id}/view', [Backend\Blog\CommentController::class, 'viewComment'])->middleware('ajax.only');
            Route::post('comments/{id}/update', [Backend\Blog\CommentController::class, 'updateComment'])->name('comments.update');
            Route::delete('comments/{id}', [Backend\Blog\CommentController::class, 'destroy'])->name('comments.destroy');
        });
        Route::prefix('settings')->namespace('Settings')->middleware('demo')->group(function () {
            Route::name('admin.settings.')->group(function () {
                Route::view('/', 'backend.settings.index')->name('index');
                Route::get('general', [Backend\Settings\GeneralController::class, 'index'])->name('general');
                Route::post('general/update', [Backend\Settings\GeneralController::class, 'update'])->name('general.update');
                Route::name('upload.')->prefix('upload')->middleware('noSaas')->group(function () {
                    Route::get('/', [Backend\Settings\UploadController::class, 'index'])->name('index');
                    Route::get('{id}', [Backend\Settings\UploadController::class, 'edit'])->name('edit');
                    Route::post('{id}', [Backend\Settings\UploadController::class, 'update'])->name('update');
                });
                Route::name('storage.')->prefix('storage')->group(function () {
                    Route::get('/', [Backend\Settings\StorageController::class, 'index'])->name('index');
                    Route::get('edit/{id}', [Backend\Settings\StorageController::class, 'edit'])->name('edit');
                    Route::post('edit/{id}', [Backend\Settings\StorageController::class, 'update'])->name('update');
                    Route::post('connect/{provider}', [Backend\Settings\StorageController::class, 'storageTest'])->name('test');
                    Route::post('default/{id}', [Backend\Settings\StorageController::class, 'setDefault'])->name('default');
                });
                Route::get('smtp', [Backend\Settings\SmtpController::class, 'index'])->name('smtp');
                Route::post('smtp/update', [Backend\Settings\SmtpController::class, 'update'])->name('smtp.update');
                Route::post('smtp/test', [Backend\Settings\SmtpController::class, 'test'])->name('smtp.test');
                Route::resource('extensions', 'ExtensionController')->only('index', 'edit', 'update');
                Route::resource('gateways', 'GatewayController')->only('index', 'edit', 'update')->middleware('saas');
                Route::name('mailtemplates.')->prefix('mailtemplates')->group(function () {
                    Route::get('/', [Backend\Settings\MailTemplateController::class, 'redirect'])->name('index');
                    Route::post('settings/update', [Backend\Settings\MailTemplateController::class, 'updateSettings'])->name('settings.update');
                    Route::get('{lang}', [Backend\Settings\MailTemplateController::class, 'index'])->name('show');
                    Route::get('{lang}/{group}', [Backend\Settings\MailTemplateController::class, 'index'])->name('show.group');
                    Route::post('{lang}/{group}', [Backend\Settings\MailTemplateController::class, 'update'])->name('update');
                });
                Route::resource('taxes', 'TaxController')->middleware('saas');
            });
            Route::get('pages/slug', [Backend\Settings\PageController::class, 'slug'])->name('pages.slug');
            Route::resource('pages', 'PageController');
            Route::resource('admins', 'AdminController');
            Route::prefix('languages')->group(function () {
                Route::post('settings/update', [Backend\Settings\LanguageController::class, 'updateSettings'])->name('language.settings.update');
                Route::post('{id}/default', [Backend\Settings\LanguageController::class, 'setDefault'])->name('language.default');
                Route::post('{id}/update', [Backend\Settings\LanguageController::class, 'translateUpdate'])->name('translates.update');
                Route::get('translate/{code}', [Backend\Settings\LanguageController::class, 'translate'])->name('language.translate');
                Route::get('translate/{code}/{group}', [Backend\Settings\LanguageController::class, 'translate'])->name('language.translate.group');
            });
            Route::resource('languages', 'LanguageController');
            Route::resource('seo', 'SeoController');
        });
        Route::name('admin.additional.')->prefix('additional')->namespace('Additional')->middleware('demo')->group(function () {
            Route::get('cache', [Backend\Additional\CacheController::class, 'index'])->name('cache');
            Route::get('custom-css', [Backend\Additional\CustomCssController::class, 'index'])->name('css');
            Route::post('custom-css/update', [Backend\Additional\CustomCssController::class, 'update'])->name('css.update');
            Route::get('popup-notice', [Backend\Additional\PopupNoticeController::class, 'index'])->name('notice');
            Route::post('popup-notice/update', [Backend\Additional\PopupNoticeController::class, 'update'])->name('notice.update');
        });
        Route::name('admin.')->prefix('others')->namespace('Others')->middleware('demo')->group(function () {
            Route::resource('slideshow', 'SlideShowController');
            Route::resource('features', 'FeatureController');
            Route::resource('faq', 'FaqController');
            Route::get('download-page', [Backend\Others\DownloadPageController::class, 'index']);
            Route::post('download-page', [Backend\Others\DownloadPageController::class, 'update'])->name('download.page');
        });
        Route::name('admin.')->prefix('account')->namespace('Account')->middleware('demo')->group(function () {
            Route::get('details', [Backend\Account\SettingsController::class, 'detailsForm'])->name('account.details');
            Route::get('security', [Backend\Account\SettingsController::class, 'securityForm'])->name('account.security');
            Route::post('details/update', [Backend\Account\SettingsController::class, 'detailsUpdate'])->name('account.details.update');
            Route::post('security/update', [Backend\Account\SettingsController::class, 'securityUpdate'])->name('account.security.update');
        });
    });
});

/*
|--------------------------------------------------------------------------
| Frontend Routs With Laravel Localization

app/Models/Feature.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Feature extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'lang',
        'title',
        'image',
        'content',
        'link',
    ];
}

app/Http/Controllers/Backend/Others/DownloadPageController.php
<?php

namespace App\Http\Controllers\Backend\Others;

use App\Http\Controllers\Controller;
use App\Models\Additional;
use Illuminate\Http\Request;

class DownloadPageController extends Controller
{
    public function index(): \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
    {
        return view('backend.others.downloadPage.index');
    }

    public function update(Request $request): \Illuminate\Http\RedirectResponse
    {
        $request->download_page_center_section_status = ($request->has('download_page_center_section_status')) ? 1 : 0;
        $request->download_page_bottom_section_status = ($request->has('download_page_bottom_section_status')) ? 1 : 0;
        $additionals = Additional::whereIn('key', [
            'download_page_center_section_status',
            'download_page_center_section_title',
            'download_page_center_section_content',
            'download_page_bottom_section_status',
            'download_page_bottom_section_title',
            'download_page_bottom_section_content',
        ])->get();
        foreach ($additionals as $additional) {
            $key = $additional->key;
            $additional->value = $request->$key;
            $additional->save();
        }
        toastr()->success(__('Updated Successfully'));

        return redirect()->back();
    }
}

app/Http/Controllers/Backend/Others/FaqController.php
<?php

namespace App\Http\Controllers\Backend\Others;

use App\Http\Controllers\Controller;
use App\Models\Faq;
use App\Models\Language;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class FaqController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->has('lang')) {
            $language = Language::where('code', $request->lang)->firstOrFail();
            $faqs = Faq::where('lang', $language->code)->get();

            return view('backend.others.faq.index', ['faqs' => $faqs, 'active' => $language->name]);
        }
        return redirect(url()->current().'?lang='.config('settings.default_language'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(): \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
    {
        return view('backend.others.faq.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'lang' => ['required', 'string', 'max:3'],
            'title' => ['required', 'string', 'max:255'],
            'content' => ['required', 'string'],
        ]);
        if ($validator->fails()) {
            foreach ($validator->errors()->all() as $error) {
                toastr()->error($error);
            }

            return redirect()->back()->withInput();
        }
        $lang = Language::where('code', $request->lang)->first();
        if ($lang == null) {
            toastr()->error(__('Language not exists'));

            return redirect()->back();
        }
        $create = Faq::create([
            'lang' => $lang->code,
            'title' => $request->title,
            'content' => $request->content,
        ]);
        if ($create) {
            toastr()->success(__('Created Successfully'));

            return redirect(route('admin.faq.index').'?lang='.$create->lang);
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(Faq $faq): \Illuminate\Http\Response
    {
        return abort(404);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Faq $faq): \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
    {
        return view('backend.others.faq.edit', ['faq' => $faq]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Faq $faq)
    {
        $validator = Validator::make($request->all(), [
            'lang' => ['required', 'string', 'max:3'],
            'title' => ['required', 'string', 'max:255'],
            'content' => ['required', 'string'],
        ]);
        if ($validator->fails()) {
            foreach ($validator->errors()->all() as $error) {
                toastr()->error($error);
            }

            return redirect()->back()->withInput();
        }
        $lang = Language::where('code', $request->lang)->first();
        if ($lang == null) {
            toastr()->error(__('Language not exists'));

            return redirect()->back();
        }
        $update = $faq->update([
            'lang' => $lang->code,
            'title' => $request->title,
            'content' => $request->content,
        ]);
        if ($update) {
            toastr()->success(__('Updated Successfully'));

            return redirect()->back();
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Faq $faq): \Illuminate\Http\RedirectResponse
    {
        $faq->delete();
        toastr()->success(__('Deleted Successfully'));

        return redirect()->back();
    }
}

resources/views/backend/others/features/create.blade.php
@extends('backend.layouts.form')
@section('title', __('Create feature'))
@section('back', route('admin.features.index'))
@section('container', 'container-max-lg')
@section('content')
    <form id="vironeer-submited-form" action="{{ route('admin.features.store') }}" method="POST"
        enctype="multipart/form-data">
        @csrf
        <div class="card mb-3">
            <div class="card-body">
                <div class="vironeer-file-preview-box mb-3 bg-light p-4 text-center">
                    <div class="file-preview-box mb-3 d-none">
                        <img id="filePreview" src="#" class="rounded-3" height="100" width="100">
                    </div>
                    <button id="selectFileBtn" type="button"
                        class="btn btn-secondary mb-2">{{ __('Choose Image') }}</button>
                    <input id="selectedFileInput" type="file" name="image" accept="image/png, image/jpg, image/jpeg"
                        hidden required>
                    <small class="text-muted d-block">{{ __('Allowed (PNG, JPG, JPEG)') }}</small>
                    <small class="text-muted d-block">{{ __('Image will be resized into (120x120)') }}</small>
                </div>
                <div class="mb-3">
                    <label class="form-label">{{ __('Language') }} :<span class="red">*</span></label>
                    <select name="lang" class="form-select select2" required>
                        <option></option>
                        @foreach ($adminLanguages as $adminLanguage)
                            <option value="{{ $adminLanguage->code }}" @if (old('lang') == $adminLanguage->code) selected @endif>
                                {{ $adminLanguage->name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
        </div>
        <div class="card p-2">
            <div class="card-body">
                <div class="mb-3">
                    <label class="form-label">{{ __('Feature title') }} : <span class="red">*</span></label>
                    <input type="text" name="title" class="form-control" value="{{ old('title') }}" required
                        autofocus />
                </div>
                <div class="mb-0">
                    <label class="form-label">{{ __('Feature content') }} :
                        <small class="text-muted">({{ __('Max 600 characters, spaces allowed') }})</small><span
                            class="red">*</span></label>
                    <textarea name="content" rows="8" class="form-control" required>{{ old('content') }}</textarea>
                </div>
            </div>
        </div>
    </form>
@endsection

resources/views/backend/others/features/edit.blade.php
@extends('backend.layouts.form')
@section('title', $feature->title)
@section('back', route('admin.features.index'))
@section('container', 'container-max-lg')
@section('content')
    <form id="vironeer-submited-form" action="{{ route('admin.features.update', $feature->id) }}" method="POST"
        enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="card mb-3">
            <div class="card-body">
                <div class="vironeer-file-preview-box mb-3 bg-light p-4 text-center">
                    <div class="file-preview-box mb-3">
                        <img id="filePreview" src="{{ asset($feature->image) }}" class="rounded-3" height="100"
                            width="100">
                    </div>
                    <button id="selectFileBtn" type="button"
                        class="btn btn-secondary mb-2">{{ __('Choose Image') }}</button>
                    <input id="selectedFileInput" type="file" name="image" accept="image/png, image/jpg, image/jpeg"
                        hidden>
                    <small class="text-muted d-block">{{ __('Allowed (PNG, JPG, JPEG)') }}</small>
                    <small class="text-muted d-block">{{ __('Image will be resized into (120x120)') }}</small>
                </div>
                <div class="mb-3">
                    <label class="form-label">{{ __('Language') }} :<span class="red">*</span></label>
                    <select name="lang" class="form-select select2" required>
                        <option></option>
                        @foreach ($adminLanguages as $adminLanguage)
                            <option value="{{ $adminLanguage->code }}" @if ($feature->lang == $adminLanguage->code) selected @endif>
                                {{ $adminLanguage->name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
        </div>
        <div class="card p-2">
            <div class="card-body">
                <div class="mb-3">
                    <label class="form-label">{{ __('Feature title') }} : <span class="red">*</span></label>
                    <input type="text" name="title" class="form-control" value="{{ $feature->title }}" required
                        autofocus />
                </div>
                <div class="mb-0">
                    <label class="form-label">{{ __('Feature content') }} :
                        <small class="text-muted">({{ __('Max 600 characters, spaces allowed') }})</small><span
                            class="red">*</span></label>
                    <textarea name="content" rows="8" class="form-control" required>{{ $feature->content }}</textarea>
                </div>
            </div>
        </div>
    </form>
@endsection

resources/views/backend/others/features/index.blade.php
@extends('backend.layouts.grid')
@section('title', $active . ' ' . __('Features'))
@section('link', route('admin.features.create'))
@section('language', true)
@section('content')
    <div class="card">
        <table id="datatable" class="table w-100">
            <thead>
                <tr>
                    <th class="tb-w-2x">{{ __('#') }}</th>
                    <th class="tb-w-3x">{{ __('Language') }}</th>
                    <th class="tb-w-20x">{{ __('Details') }}</th>
                    <th class="tb-w-7x">{{ __('Published date') }}</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach ($features as $feature)
                    <tr class="item">
                        <td>{{ $feature->id }}</td>
                        <td><a href="{{ route('language.translate', $feature->lang) }}">{{ $feature->lang }}</a></td>
                        <td>
                            <div class="vironeer-content-box">
                                <a class="vironeer-content-image" href="{{ route('admin.features.edit', $feature->id) }}">
                                    <img src="{{ asset($feature->image) }}">
                                </a>
                                <div>
                                    <a class="text-reset"
                                        href="{{ route('admin.features.edit', $feature->id) }}">{{ shortertext($feature->title, 40) }}</a>
                                    <p class="text-muted mb-0">{{ shortertext($feature->content, 50) }}</p>
                                </div>
                            </div>
                        </td>
                        <td>{{ vDate($feature->created_at) }}</td>
                        <td>
                            <div class="text-end">
                                <button type="button" class="btn btn-sm rounded-3" data-bs-toggle="dropdown"
                                    aria-expanded="true">
                                    <i class="fa fa-ellipsis-v fa-sm text-muted"></i>
                                </button>
                                <ul class="dropdown-menu dropdown-menu-sm-end" data-popper-placement="bottom-end">
                                    <li>
                                        <a class="dropdown-item"
                                            href="{{ route('admin.features.edit', $feature->id) }}"><i
                                                class="fa fa-edit me-2"></i>{{ __('Edit') }}</a>
                                    </li>
                                    <li>
                                        <hr class="dropdown-divider" />
                                    </li>
                                    <li>
                                        <form action="{{ route('admin.features.destroy', $feature->id) }}" method="POST">
                                            @csrf @method('DELETE')
                                            <button class="vironeer-able-to-delete dropdown-item text-danger"><i
                                                    class="far fa-trash-alt me-2"></i>{{ __('Delete') }}</button>
                                        </form>
                                    </li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
@endsection