routes/web.php
<?php

use App\Http\Controllers\Backend;
use App\Http\Controllers\Frontend;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
 */

Route::middleware('notInstalled')->prefix('admin')->namespace('Backend')->group(function () {
    Route::name('admin.')->namespace('Auth')->group(function () {
        Route::get('/', [Backend\Auth\LoginController::class, 'redirectToLogin'])->name('index');
        Route::get('login', [Backend\Auth\LoginController::class, 'showLoginForm'])->name('login');
        Route::post('login', [Backend\Auth\LoginController::class, 'login'])->name('login.store');
        Route::get('password/reset', [Backend\Auth\ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.reset');
        Route::post('password/reset', [Backend\Auth\ForgotPasswordController::class, 'sendResetLinkEmail']);
        Route::get('password/reset/{token}', [Backend\Auth\ResetPasswordController::class, 'showResetForm'])->name('password.reset.link');
        Route::post('password/reset/change', [Backend\Auth\ResetPasswordController::class, 'reset'])->name('password.reset.change');
        Route::post('logout', [Backend\Auth\LoginController::class, 'logout'])->name('logout');
    });
    Route::middleware('admin')->group(function () {
        Route::name('admin.')->middleware('demo')->group(function () {
            Route::prefix('dashboard')->group(function () {
                Route::get('/', [Backend\DashboardController::class, 'index'])->name('dashboard');
                Route::get('charts/users', [Backend\DashboardController::class, 'usersChartData'])->middleware('ajax.only');
                Route::get('charts/uploads', [Backend\DashboardController::class, 'uploadsChartData'])->middleware('ajax.only');
                Route::get('charts/earnings', [Backend\DashboardController::class, 'earningsChartData'])->middleware(['saas', 'ajax.only']);
                Route::get('charts/logs', [Backend\DashboardController::class, 'logsChartData'])->middleware('ajax.only');
            });
            Route::name('notifications.')->prefix('notifications')->group(function () {
                Route::get('/', [Backend\NotificationController::class, 'index'])->name('index');
                Route::get('view/{id}', [Backend\NotificationController::class, 'view'])->name('view');
                Route::get('readall', [Backend\NotificationController::class, 'readAll'])->name('readall');
                Route::delete('deleteallread', [Backend\NotificationController::class, 'deleteAllRead'])->name('deleteallread');
            });
            Route::name('users.')->prefix('users')->group(function () {
                Route::post('{id}/edit/change/avatar', [Backend\UserController::class, 'changeAvatar']);
                Route::delete('{id}/edit/delete/avatar', [Backend\UserController::class, 'deleteAvatar'])->name('deleteAvatar');
                Route::get('{id}/edit/logs', [Backend\UserController::class, 'logs'])->name('logs');
                Route::get('{id}/edit/logs/get/{log_id}', [Backend\UserController::class, 'getLogs'])->middleware('ajax.only');
                Route::post('{id}/edit/sentmail', [Backend\UserController::class, 'sendMail'])->name('sendmail');
                Route::get('logs/{ip}', [Backend\UserController::class, 'logsByIp'])->name('logsbyip');
            });
            Route::resource('users', 'UserController');
            Route::name('uploads.')->namespace('Uploads')->prefix('uploads')->group(function () {
                Route::get('secure/{id}', [Backend\Uploads\SecureUploadController::class, 'index'])->name('secure');
                Route::name('users.')->prefix('users')->group(function () {
                    Route::get('/', [Backend\Uploads\UserUploadsController::class, 'index'])->name('index');
                    Route::get('{shared_id}/view', [Backend\Uploads\UserUploadsController::class, 'view'])->name('view');
                    Route::get('{shared_id}/download', [Backend\Uploads\UserUploadsController::class, 'downloadFile'])->name('download');
                    Route::delete('{shared_id}/delete', [Backend\Uploads\UserUploadsController::class, 'destroy'])->name('destroy');
                    Route::post('delete-selected', [Backend\Uploads\UserUploadsController::class, 'destroySelected'])->name('destroy.selected');
                });
                Route::name('guests.')->prefix('guests')->group(function () {
                    Route::get('/', [Backend\Uploads\GuestUploadsController::class, 'index'])->name('index');
                    Route::get('{shared_id}/view', [Backend\Uploads\GuestUploadsController::class, 'view'])->name('view');
                    Route::get('{shared_id}/download', [Backend\Uploads\GuestUploadsController::class, 'downloadFile'])->name('download');
                    Route::delete('{shared_id}', [Backend\Uploads\GuestUploadsController::class, 'destroy'])->name('destroy');
                    Route::post('delete-selected', [Backend\Uploads\GuestUploadsController::class, 'destroySelected'])->name('destroy.selected');
                });
            });
            Route::name('reports.')->prefix('reports')->group(function () {
                Route::get('/', [Backend\FileReportController::class, 'index'])->name('index');
                Route::get('{id}/view', [Backend\FileReportController::class, 'view'])->name('view');
                Route::post('{id}/view', [Backend\FileReportController::class, 'markAsReviewed'])->name('markAsReviewed');
                Route::delete('{id}/delete', [Backend\FileReportController::class, 'destroy'])->name('destroy');
            });
            Route::middleware('saas')->group(function () {
                Route::resource('subscriptions', 'SubscriptionController');
                Route::resource('transactions', 'TransactionController');
                Route::resource('plans', 'PlanController');
                Route::resource('coupons', 'CouponController');
            });
            Route::get('advertisements', [Backend\AdvertisementController::class, 'index'])->name('advertisements.index');
            Route::get('advertisements/{id}/edit', [Backend\AdvertisementController::class, 'edit'])->name('advertisements.edit');
            Route::post('advertisements/{id}', [Backend\AdvertisementController::class, 'update'])->name('advertisements.update');
        });
        Route::prefix('navigation')->namespace('Navigation')->name('admin.')->middleware('demo')->group(function () {
            Route::post('navbarMenu/sort', [Backend\Navigation\NavbarMenuController::class, 'sort'])->name('navbarMenu.sort');
            Route::resource('navbarMenu', 'NavbarMenuController');
            Route::post('footerMenu/sort', [Backend\Navigation\FooterMenuController::class, 'sort'])->name('footerMenu.sort');
            Route::resource('footerMenu', 'FooterMenuController');
        });
        Route::prefix('blog')->namespace('Blog')->middleware('demo', 'disable.blog')->group(function () {
            Route::get('categories/slug', [Backend\Blog\CategoryController::class, 'slug'])->name('categories.slug');
            Route::resource('categories', 'CategoryController');
            Route::get('articles/slug', [Backend\Blog\ArticleController::class, 'slug'])->name('articles.slug');
            Route::get('articles/categories/{lang}', [Backend\Blog\ArticleController::class, 'getCategories'])->middleware('ajax.only');
            Route::resource('articles', 'ArticleController');
            Route::get('comments', [Backend\Blog\CommentController::class, 'index'])->name('comments.index');
            Route::get('comments/{id}/view', [Backend\Blog\CommentController::class, 'viewComment'])->middleware('ajax.only');
            Route::post('comments/{id}/update', [Backend\Blog\CommentController::class, 'updateComment'])->name('comments.update');
            Route::delete('comments/{id}', [Backend\Blog\CommentController::class, 'destroy'])->name('comments.destroy');
        });
        Route::prefix('settings')->namespace('Settings')->middleware('demo')->group(function () {
            Route::name('admin.settings.')->group(function () {
                Route::view('/', 'backend.settings.index')->name('index');
                Route::get('general', [Backend\Settings\GeneralController::class, 'index'])->name('general');
                Route::post('general/update', [Backend\Settings\GeneralController::class, 'update'])->name('general.update');
                Route::name('upload.')->prefix('upload')->middleware('noSaas')->group(function () {
                    Route::get('/', [Backend\Settings\UploadController::class, 'index'])->name('index');
                    Route::get('{id}', [Backend\Settings\UploadController::class, 'edit'])->name('edit');
                    Route::post('{id}', [Backend\Settings\UploadController::class, 'update'])->name('update');
                });
                Route::name('storage.')->prefix('storage')->group(function () {
                    Route::get('/', [Backend\Settings\StorageController::class, 'index'])->name('index');
                    Route::get('edit/{id}', [Backend\Settings\StorageController::class, 'edit'])->name('edit');
                    Route::post('edit/{id}', [Backend\Settings\StorageController::class, 'update'])->name('update');
                    Route::post('connect/{provider}', [Backend\Settings\StorageController::class, 'storageTest'])->name('test');

app/Http/Controllers/Backend/Account/SettingsController.php
<?php

namespace App\Http\Controllers\Backend\Account;

use App\Http\Controllers\Controller;
use App\Models\Admin;
use Illuminate\Support\Facades\Hash;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class SettingsController extends Controller
{
    public function detailsForm(): \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
    {
        return view('backend.account.details');
    }

    public function detailsUpdate(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'firstname' => ['required', 'string', 'max:255'],
            'lastname' => ['required', 'string', 'max:255'],
            'avatar' => ['image', 'mimes:png,jpg,jpeg', 'max:2048'],
            'email' => ['required', 'email', 'unique:admins,email,'.$this->admin()->id],
        ]);
        if ($validator->fails()) {
            foreach ($validator->errors()->all() as $error) {
                toastr()->error($error);
            }

            return redirect()->back();
        }
        if ($request->has('avatar')) {
            if ($this->admin()->avatar == 'images/avatars/default.png') {
                $uploadAvatar = vImageUpload($request->file('avatar'), 'images/avatars/admins/', '110x110');
            } else {
                $uploadAvatar = vImageUpload($request->file('avatar'), 'images/avatars/admins/', '110x110', null, $this->admin()->avatar);
            }
        } else {
            $uploadAvatar = $this->admin()->avatar;
        }
        $update = Admin::where('id', $this->admin()->id)->update([
            'firstname' => $request->firstname,
            'lastname' => $request->lastname,
            'email' => $request->email,
            'avatar' => $uploadAvatar,
        ]);
        if ($update) {
            toastr()->success(__('Updated Successfully'));

            return redirect()->back();
        }
    }

    public function securityForm(): \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
    {
        return view('backend.account.security');
    }

    public function securityUpdate(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'current-password' => ['required'],
            'new-password' => ['required', 'string', 'min:6', 'confirmed'],
            'new-password_confirmation' => ['required'],
        ]);
        if ($validator->fails()) {
            foreach ($validator->errors()->all() as $error) {
                toastr()->error($error);
            }

            return redirect()->back();
        }
        if (! (Hash::check($request->get('current-password'), $this->admin()->password))) {
            toastr()->error(__('Your current password does not matches with the password you provided.'));

            return redirect()->back();
        }
        if (strcmp($request->get('current-password'), $request->get('new-password')) == 0) {
            toastr()->error(__('New Password cannot be same as your current password. Please choose a different password.'));

            return redirect()->back();
        }
        $update = Admin::where('id', $this->admin()->id)->update([
            'password' => bcrypt($request->get('new-password')),
        ]);
        if ($update) {
            toastr()->success(__('Updated Successfully'));

            return redirect()->back();
        }
    }

    protected function admin()
    {
        $admin = Admin::find(adminAuthInfo()->id);

        return $admin;
    }
}

app/Http/Controllers/Backend/Additional/CacheController.php
<?php

namespace App\Http\Controllers\Backend\Additional;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Artisan;

class CacheController extends Controller
{
    public function index(): \Illuminate\Http\RedirectResponse
    {
        Artisan::call('optimize:clear');
        removeFile(storage_path('logs/laravel.log'));
        toastr()->success(__('Cache Cleared Successfully'));

        return redirect()->back();
    }
}

app/Http/Controllers/Backend/Additional/CustomCssController.php
<?php

namespace App\Http\Controllers\Backend\Additional;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CustomCssController extends Controller
{
    public function index(): \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
    {
        $cssFile = @file_get_contents('assets/css/extra/custom.css');

        return view('backend.additional.custom-css', ['cssFile' => $cssFile]);
    }

    public function update(Request $request): \Illuminate\Http\RedirectResponse
    {
        $cssFile = 'assets/css/extra/custom.css';
        if (! file_exists($cssFile)) {
            fopen($cssFile, 'w');
        }
        file_put_contents($cssFile, $request->cssContent);
        toastr()->success(__('Updated Successfully'));

        return redirect()->back();
    }
}

app/Http/Controllers/Backend/Additional/PopupNoticeController.php
<?php

namespace App\Http\Controllers\Backend\Additional;

use App\Http\Controllers\Controller;
use App\Models\Additional;
use Illuminate\Http\Request;

class PopupNoticeController extends Controller
{
    public function index(): \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
    {
        return view('backend.additional.popup-notice');
    }

    public function update(Request $request): \Illuminate\Http\RedirectResponse
    {
        $request->popup_notice_status = ($request->has('popup_notice_status')) ? 1 : 0;
        $additionals = Additional::whereIn('key', ['popup_notice_status', 'popup_notice_description'])->get();
        foreach ($additionals as $additional) {
            $key = $additional->key;
            $additional->value = $request->$key;
            $additional->save();
        }
        toastr()->success(__('Updated Successfully'));

        return redirect()->back();
    }
}

app/Http/Controllers/Backend/AdvertisementController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Advertisement;
use Illuminate\Http\Request;

class AdvertisementController extends Controller
{
    public function index(): \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
    {
        $advertisements = Advertisement::all();
        $headAd = Advertisement::where('symbol', 'head_code')->first();

        return view('backend.advertisements.index', ['advertisements' => $advertisements, 'headAd' => $headAd]);
    }

    public function edit($id): \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
    {
        $advertisement = Advertisement::findOrFail($id);

        return view('backend.advertisements.edit', ['advertisement' => $advertisement]);
    }

    public function update(Request $request, $id)
    {
        if ($request->has('status') && is_null($request->code)) {
            toastr()->error(__('Advertisement code cannot be empty'));

            return redirect()->back();
        }
        $request->status = ($request->has('status')) ? 1 : 0;
        $update = Advertisement::where('id', $id)->update([
            'code' => $request->code,
            'status' => $request->status,
        ]);
        if ($update) {
            toastr()->success(__('Updated Successfully'));

            return redirect()->back();
        }
    }
}

resources/views/backend/reports/index.blade.php
@extends('backend.layouts.grid')
@section('title', __('Reported files'))
@section('content')
    <div class="row g-3 mb-4">
        <div class="col-12 col-lg-4 col-xxl">
            <div class="vironeer-counter-box bg-c-7 h-100">
                <h3 class="vironeer-counter-box-title">{{ __('Waiting review') }}</h3>
                <p class="vironeer-counter-box-number">{{ formatNumber($waitingReview) }}</p>
                <span class="vironeer-counter-box-icon">
                    <i class="far fa-clock"></i>
                </span>
            </div>
        </div>
        <div class="col-12 col-lg-4 col-xxl">
            <div class="vironeer-counter-box bg-c-4 h-100">
                <h3 class="vironeer-counter-box-title">{{ __('Reviewed') }}</h3>
                <p class="vironeer-counter-box-number">{{ formatNumber($reviewed) }}</p>
                <span class="vironeer-counter-box-icon">
                    <i class="far fa-check-circle"></i>
                </span>
            </div>
        </div>
    </div>
    <div class="card custom-card">
        <table id="datatable" class="table w-100">
            <thead>
                <tr>
                    <th class="tb-w-3x">{{ __('#') }}</th>
                    <th class="tb-w-20x">{{ __('File details') }}</th>
                    <th class="tb-w-3x">{{ __('Reported by') }}</th>
                    <th class="tb-w-3x">{{ __('Report reason') }}</th>
                    <th class="tb-w-5x">{{ __('Status') }}</th>
                    <th class="tb-w-7x">{{ __('Report date') }}</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach ($fileReports as $fileReport)
                    <tr class="item">
                        <td>{{ $fileReport->id }}</td>
                        <td>
                            <div class="vironeer-content-box">
                                <a class="vironeer-content-image text-center"
                                    href="{{ route($fileReport->fileEntry->user_id ? 'admin.uploads.users.view' : 'admin.uploads.guests.view', $fileReport->fileEntry->shared_id) }}">
                                    @if ($fileReport->fileEntry->type == 'image')
                                        <img src="{{ route('admin.uploads.secure', hashid($fileReport->fileEntry->id)) }}"
                                            alt="{{ $fileReport->fileEntry->name }}">
                                    @else
                                        {!! fileIcon($fileReport->fileEntry->extension) !!}
                                    @endif
                                </a>
                                <div>
                                    <a class="text-reset"
                                        href="{{ route($fileReport->fileEntry->user_id ? 'admin.uploads.users.view' : 'admin.uploads.guests.view', $fileReport->fileEntry->shared_id) }}">
                                        {{ shortertext($fileReport->fileEntry->name, 50) }}
                                    </a>
                                    <p class="text-muted mb-0">
                                        {{ shortertext($fileReport->fileEntry->mime, 50) ?? __('Unknown') }}</p>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="vironeer-content-box">
                                <div>
                                    <span>{{ shortertext($fileReport->name, 30) }}</span>
                                    <p class="text-muted mb-0">{{ shortertext($fileReport->email, 30) }}</p>
                                </div>
                            </div>
                        </td>
                        <td>{{ shortertext(reportReasons()[$fileReport->reason], 25) }}</td>
                        <td>
                            @if ($fileReport->admin_has_viewed)
                                <span class="badge bg-success">{{ __('Reviewed') }}</span>
                            @else
                                <span class="badge bg-c-7">{{ __('Waiting review') }}</span>
                            @endif
                        </td>
                        <td>{{ vDate($fileReport->created_at) }}</td>
                        <td>
                            <div class="text-end">
                                <button type="button" class="btn btn-sm rounded-3" data-bs-toggle="dropdown"
                                    aria-expanded="true">
                                    <i class="fa fa-ellipsis-v fa-sm text-muted"></i>
                                </button>
                                <ul class="dropdown-menu dropdown-menu-sm-end dropdown-menu-lg"
                                    data-popper-placement="bottom-end">
                                    <li>
                                        <a class="dropdown-item"
                                            href="{{ route('admin.reports.view', $fileReport->id) }}"><i
                                                class="fa fa-desktop me-2"></i>{{ __('Report Details') }}</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item"
                                            href="{{ route($fileReport->fileEntry->user_id ? 'admin.uploads.users.view' : 'admin.uploads.guests.view', $fileReport->fileEntry->shared_id) }}"
                                            target="_blank"><i class="fa fa-eye me-2"></i>{{ __('Reported File') }}</a>
                                    </li>
                                    <li>
                                        <hr class="dropdown-divider" />
                                    </li>
                                    <li>
                                        <form action="{{ route('admin.reports.destroy', $fileReport->id) }}"
                                            method="POST">
                                            @csrf @method('DELETE')
                                            <button class="vironeer-able-to-delete dropdown-item text-danger"><i
                                                    class="far fa-trash-alt me-2"></i>{{ __('Delete') }}</button>
                                        </form>
                                    </li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @push('styles_libs')
        <link rel="stylesheet" href="{{ asset('assets/vendor/libs/vironeer/vironeer-icons.min.css') }}">
    @endpush
@endsection

resources/views/backend/reports/view.blade.php
@extends('backend.layouts.grid')
@section('section', __('Reported files'))
@section('title', __('Report | #') . $fileReport->id)
@section('back', route('admin.reports.index'))
@section('container', 'container-max-lg')
@section('content')
    <div class="card custom-card mb-2">
        <div class="card-header bg-c-7 text-white">
            {{ __('Report details') }}
        </div>
        <div class="card-body">
            <div class="d-flex align-items-center">
                <div class="flex-shrink-0">
                    <a href="{{ route($fileReport->fileEntry->user_id ? 'admin.uploads.users.view' : 'admin.uploads.guests.view', $fileReport->fileEntry->shared_id) }}"
                        target="_blank">
                        @if ($fileReport->fileEntry->type == 'image')
                            <img class="rounded-2"
                                src="{{ route('admin.uploads.secure', hashid($fileReport->fileEntry->id)) }}"
                                alt="{{ $fileReport->fileEntry->name }}" width="60" height="60">
                        @else
                            {!! fileIcon($fileReport->fileEntry->extension) !!}
                        @endif
                    </a>
                </div>
                <div class="flex-grow-1 ms-3">
                    <a href="{{ route($fileReport->fileEntry->user_id ? 'admin.uploads.users.view' : 'admin.uploads.guests.view', $fileReport->fileEntry->shared_id) }}"
                        target="_blank" class="text-dark">
                        <h5 class="mb-1">{{ shortertext($fileReport->fileEntry->name, 100) }}</h5>
                        <p class="mb-0 text-muted">{{ shortertext($fileReport->fileEntry->mime, 50) ?? __('Unknown') }}
                        </p>
                    </a>
                </div>
                <div class="flex-grow-3 ms-3">
                    <a href="{{ route($fileReport->fileEntry->user_id ? 'admin.uploads.users.view' : 'admin.uploads.guests.view', $fileReport->fileEntry->shared_id) }}"
                        target="_blank" class="btn btn-dark" target="_blank"><i
                            class="fa fa-eye me-2"></i>{{ __('View file details') }}</a>
                </div>
            </div>
        </div>
    </div>
    <div class="card custom-card mb-3">
        <div class="card-body">
            <div class="row g-3 mb-3">
                <div class="col-lg-6">
                    <label class="form-label">{{ __('Name') }} :</label>
                    <input type="name" class="form-control form-control-lg" value="{{ $fileReport->name }}" readonly>
                </div>
                <div class="col-lg-6">
                    <label class="form-label">{{ __('Email') }} :</label>
                    <input type="email" class="form-control form-control-lg" value="{{ $fileReport->email }}" readonly>
                </div>
            </div>
            <div class="mb-3">
                <label class="form-label">{{ __('Reason for reporting') }} :</label>
                <input type="email" class="form-control form-control-lg"
                    value="{{ reportReasons()[$fileReport->reason] }}" readonly>
            </div>
            <div class="mb-2">
                <label class="form-label">{{ __('Details') }} :</label>
                <textarea class="form-control" rows="8" readonly>{{ $fileReport->details }}</textarea>
            </div>
        </div>
    </div>
    <div class="card custom-card">
        <div class="card-body">
            <div class="row g-3">
                <div class="{{ $fileReport->admin_has_viewed ? 'col-lg-12' : 'col-lg-6' }}">
                    <form action="{{ route('admin.reports.destroy', $fileReport->id) }}" method="POST">
                        @csrf @method('DELETE')
                        <button class="vironeer-able-to-delete btn btn-danger btn-lg w-100"><i
                                class="far fa-trash-alt me-2"></i>{{ __('Delete') }}</button>
                    </form>
                </div>
                @if (!$fileReport->admin_has_viewed)
                    <div class="col-lg-6">
                        <form action="{{ route('admin.reports.markAsReviewed', $fileReport->id) }}" method="POST">
                            @csrf
                            <button class="vironeer-form-confirm btn btn-success btn-lg w-100"><i
                                    class="far fa-check-circle me-2"></i>{{ __('Mark as reviewed') }}</button>
                        </form>
                    </div>
                @endif
            </div>
        </div>
    </div>
    @push('styles_libs')
        <link rel="stylesheet" href="{{ asset('assets/vendor/libs/vironeer/vironeer-icons.min.css') }}">
    @endpush
@endsection